apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  plugins:
    - monitoring-plugin
    - networking-console-plugin
    - gitops-plugin
    - kuadrant-console-plugin
