apiVersion: kuadrant.io/v1
kind: DNSPolicy
metadata:
  name: api-gateway-dns
  namespace: api-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: api-gateway
  providerRefs:
    - name: aws-dns-credentials
