apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-api-gateway-tls
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: api-gateway
  to:
    - group: ""
      kind: Secret
      name: default-ingress-cert
