apiVersion: v1
kind: Secret
metadata:
  name: demo-user-api-key
  namespace: sample-app
  labels:
    app: sample-app-api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    secret.kuadrant.io/plan-id: "bronze"
type: Opaque
stringData:
  api_key: "demo-api-key-sample-app-12345"
