apiVersion: v1
kind: Secret
metadata:
  name: demo-user-api-key
  namespace: sample-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  api_key: "demo-api-key-sample-app-12345"
