apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: sample-app-auth
  namespace: sample-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: sample-app
  rules:
    authorization:
      allow-all:
        opa:
          rego: "allow = true"
