apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - auth-policy.yaml
  - plan-policy.yaml
  - api-key-secret.yaml
  - api-product.yaml
  - api-key.yaml
  - api-key-request.yaml
