apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  username: keycloak
  password: keycloak-db-password
